version: '3.4'

services:
  antino-ai-be:
    image: antino-ai-be
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antino-ai-be
    env_file:
      - .env.dev
    restart: always
    ports:
      - "7009:3000"
    networks:
      - gmr-dpr-be_default
networks:
  gmr-dpr-be_default:
    external: true
